### PR TITLE
bug-fix: the epoch number from some beacons is outdated

### PR DESCRIPTION
**Pull request by ijaa**
In the process of switching beacon nodes, the epoch number returned by some beacon nodes are outdated, and these nodes need to be skipped

### CODE REVIEW

**Comment by HarukaMa** [comment]
It’s already being checked in server.rs; any specific reason that we need to check here as well?

**Comment by ijaa** [comment]
because the wrong epoch number is still be stored in server.rs and this will affect the validity confirmation of the solution message returned by the provers.

**Comment by HarukaMa** [comment]
Got it, I was thinking about the similar checks in the prover as it is correct there; obviously the check in the pool server is wrong.

https://github.com/HarukaMa/aleo-pool-server/blob/c1d535de6245505e8c59b6d40cd1d5723d96b447/src/server.rs#L400-L401

I'd prefer to not check it twice though, so I think you can fix this incorrect check instead: make sure the epoch of the new challenge is greater than the current one, and for extra safety, both the new challenge and the current challenge should have epoch 0 to be accepted (this is for challenges with epoch 0 as changing the store to `AtomicI32` will lead to a lot of unnecessary castings later).

I think it was `!=` because in testnet2 there were many forks so the block height would rewind from time to time.

**Comment by ijaa** [comment]
yee, the `!=` can be changed for the wrong epoch number to be stored, but on the other hand, if the current connected beacon node keeps return the outdated epoch number, It will affect the timeliness of value update for ` latest_epoch_number`  in `server.rs`, and this also affect the all provers

**Comment by HarukaMa** [comment]
the pool server only connects to one node ever, so if this node refuses to return a newer challenge, changing the code will do nothing as the server don't have other data sources. You will need to make sure the node you are connected to is up-to-date. 

I've seen some nodes using old challenges; that might be a bug in snarkOS, or it's just some connection issue where the node is not connected to the official validators. That's another issue though.

**Comment by ijaa** [comment]
oo,I have changed the code ever before for selecting a new node when` break` from the `loop`.
ok, i see, maybe some nodes is not connected to the official validators.
Thx, I will close this pr.

**Pull request closed without merging**
